default: &default
  adapter: postgresql
  encoding: utf8
  port: <%= ENV['DB_PORT'] %>
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
